=== Actuator

Ajouter la dépendance actuator à votre projet et vérifier qu'elle fonctionne

Les endpoints sont sous localhost:8080/actuator

Par exemple localhost:8080/actuator/info

=== Profiles dans Info

En utilisant l'approche @Value, ajouter la liste des profiles spring actifs (la valeur passé en variable d'environnement)

La réponse de /actuator/info doit contenir `"profiles": "dev"` en cas de profile dev `"profiles": ""` sans

=== Info custom

Ajouter au fichier de properties

[source,yaml]
----
iut:
  spring:
    exo: 6
----

En utilisant l'approche @ConfigurationProperties ajouter le contenu à /actuator/info qui doit donc répondre:

[source,json]
----
{
    "profile": "dev",
    "iut": {
        "spring": {
            "exo": 6
        }
    }
}
----

=== Sécurité

Certains endpoints de l'actuator éxposent des données sensibles voir sont dangereux

En modifiant les properties sans profile il ne doit y avoir que health, info et metrics.
Avec le profile dev, shutdown est disponible.

Changer le port des actuators pour le port 9001
