=== Beans

En utilisant les conditions sur les beans, faire en sorte que :

- sans profil, la base h2 soit utilisée,

- avec le profil dev la version inMemory soit utilisée.

=== Logs

Modifier les logs pour qu'ils soient sous la forme : 

`INFO - class - threadId - message`

Ajouter des logs info au début des appels HTTP et de debug dans les repositories.

=== Actionneurs

Ajouter la dépendance actuator à votre projet et vérifier qu'elle fonctionne.

Les endpoints sont sous localhost:8080/actuator.

Par exemple : localhost:8080/actuator/info.

=== Profils dans Info

En utilisant l'approche @Value, ajouter la liste des profils Spring actifs (la valeur passée en variable d'environnement).

La réponse de /actuator/info doit contenir `"profiles": "dev"` en cas de profil dev `"profiles": ""` sinon.

=== Info custom

Ajouter au fichier de propriétés : 

[source,yaml]
----
iut:
  spring:
    exo: 6
----

En utilisant l'approche @ConfigurationProperties, ajouter le contenu à /actuator/info qui doit donc répondre :

[source,json]
----
{
    "profile": "dev",
    "iut": {
        "spring": {
            "exo": 6
        }
    }
}
----

=== Sécurité

Certains endpoints de l'actionneur exposent des données sensibles, voire sont dangereux.

En modifiant les propriétés sans profil, il ne doit y avoir que : health, info et metrics.
Avec le profil dev : shutdown est disponible.

Changer le port des actionneurs pour le port 9001.
