== TD1

Checkout de https://github.com/Zomzog/2024-iut-td.git

Importer le projet dans son IDE

Les modifications sont à faire dans le module Exo1

== Exo 0

Créer une implémentation de Database nommé `ListDatabase``,
cette implémentation utilisera une liste en mémoire pour la persistance.

== Exo 1

En utilisant l'approche des @Bean,
créer un fichier AppConfig qui gère la création des beans movieservice et Database

Dans la classe de test Exercice#exo1_1 charger le context Spring à partir de AppConfig
pour obtenir une instance de movieservice

== Exo 2

Avec la même approche, 
ajouter la création d'un bean Supermovieservice.

Il doit partager la même instance de `Database`.

Dans la classe de test Exercice#exo1_2 charger le context Spring à partir de AppConfig
pour obtenir une instance des services

Le test doit passer.

== Exo 3

Faire en sorte que partagent plus la même instance de `Database`

Dans la classe de test Exercice#exo1_3 charger le context Spring à partir de AppConfig
pour obtenir une instance des services.

Le test doit passer, le test exo1_2 ne passe plus.

== Exo 4

Supprimer le constructeur de Supermovieservice et utiliser l'injection avec Autowired pour ce service.

Le test exo1_3 doit toujours fonctionner

== Exo 5

Remplacer la création du bean `Database` en utilisant le stereotype `@Repository`

Le test exo1_3 doit toujours fonctionner

== Exo 6

Créer une classe de test unitaires ListDatabaseTest qui couvre à 100% ListDatabase

== Exo 6

Créer une nouvelle version de Database nommée `HashDatabase` en utilisant une `Map<UUID, User>` comme persistance.

Elle doit répondre aux mêmes tests que ListDatabaseTest

== Exo 7

Dans AppConfig créer le bean de HashDatabase en scope Singleton
Utiliser ce bean pour supermovieservice. 

Le test suivant doit passer

```kotlin
@Test
fun exo1_7() {
    val context = AnnotationConfigApplicationContext(AppConfig::class.java)
    val movieservice = context.getBean(movieservice::class.java)
    val supermovieservice = context.getBean(Supermovieservice::class.java)

    assertThat(movieservice.database).isInstanceOf(ListDatabase::class)
    assertThat(supermovieservice.database).isInstanceOf(HashDatabase::class)
}
```

== Exo 8

Ajouter les dépendances `org.springframework.boot:spring-boot-starter` et `org.springframework.boot:spring-boot-starter-test`

Remplacer tout ce qui est possible par l'utilisation de l'annotation SpringBootApplication dans le main

Le test suivant doit passer.

```kotlin
@SpringBootTest
class Exo8 {

    @Autowired
    private lateinit var movieservice: movieservice

    @Test
    fun exo_8() {
        // Test le chargement du contexte
    }
}
```

== Exo 9

Ajouter les dépendances de test `io.mockk:mockk-jvm:1.13.12` et `com.ninja-squad:springmockk:4.0.2`

Dans la class Exo8, 
remplacer la Database de movieservice par un mock.

Ajouter ce test et le compléter pour qu'il soit valide.

```
@Test
fun exo_9() {
    // GIVEN TODO

    // THEN
    assertThrows<NoSuchElementException> { movieservice.delete(user()) }
    movieservice.delete(user(UUID.randomUUID()))
}
```

== Exo 10

A partir de cet exercice, les modifications seront à faire dans le module Exo10

Créer HelloController.kt dans un sous-package controller.

[source,kotlin]
----
@RestController
class HelloController {

    @GetMapping("/hello")
    fun hello() = "world"
}
----

=== Lancer && tester

Lancer **Application.kt qui est à la racine du projet (clic droit -> run).

Appeler GET 192.168.1.44:8080/hello et vérifier que la réponse est bien world.

Par exemple en CURL

```bash
curl -XGET -v 192.168.1.44:8080/hello
...
< HTTP/1.1 200
...
world
```

== CRUD

Le but de la suite des exercices est de créer un premier CRUD (Create, Read, Update, Delete).

Le CRUD doit manipuler des films dont on a les informations: Nom, Date de sortie, Note, List des langues

Pour cette implémentation, une Map en mémoire permettra de faire office de base de données.
La clé unique est le nom du film.

La map peut-être initialisé avec une liste de film (cf MOVIES dans la classe Movie)

L'implémentation se fera dans une classe MovieController.


== Exo 11: Create

Le premier endpoint POST `/api/movies` qui prend le JSON d'un film, l'enregistre dans la Map et répond un HTTP 201 avec le contenu du film en body.
Exemple d'appel:
----
curl --location '192.168.1.44:8080/api/movies' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Jurassic Park",
    "rating": 91,
    "releaseDate": 1993,
    "languages": [ "VO", "VFF", "VFQ"]
}'
----

== Exo 12: Create - Conflit

Un endpoint de création doit normalement signaler si la ressource existe déjà.

Modifier le endpoint pour que si on envoie deux fois la même nom de film, la réponse soit un HTTP 409 (conflit).

Exemple d'appel:
----
curl --location '192.168.1.44:8080/api/movies' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Jurassic Park",
    "rating": 91,
    "releaseDate": 1993,
    "languages": [ "VO", "VFF", "VFQ"]
}' &&
curl --location '192.168.1.44:8080/api/movies' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Jurassic Park",
    "rating": 90,
    "releaseDate": 1992,
    "languages": [ "VO" ]
}'
----

== Exo 13: Read - List

Le premier endpoint de lecture est un endpoint de liste.
Un appel à GET `/api/movies` doit répondre 200 avec la liste des utilisateurs qui sont dans la Map.


Exemple d'appel:
----
curl --location '192.168.1.44:8080/api/movies'
----
Reponse:
[source,json]
----
[
  {
    "name": "The Dark Knight",
    "releaseDate": 2008,
    "rating": 9,
    "languages": [
      "VO"
    ]
  }
]
----

== Exo 14: Read - Unique

Ajouter un endpoint GET `/api/movies/{name}` qui retourne :

- un status 200 avec le contenu du film s'il existe dans la Map,
- un status 404 sinon.

Exemple d'appel:
----
curl -v --location '192.168.1.44:8080/api/movies/Dune'

HTTP/1.1 404
----

----
curl --location '192.168.1.44:8080/api/movies/Inception'
----
Reponse:
[source,json]
----
{
    "name": "Inception",
    "releaseDate": 2010,
    "rating": 8,
    "languages": [
      "VF"
    ]
}
----

== Exo 15: Update
Ajouter un endpoint PUT `/api/movies/{name}` qui retourne :

- un status 400 si la requête est invalide
- un status 404 si le film n'existe pas
- un status 200 sinon met à jour le film dans la Map et le retourne,

Exemple d'appel:
----
curl --location --request PUT '192.168.1.44:8080/api/movies/Inception' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Inception",
    "releaseDate": 2010,
    "rating": 87,
    "languages": [
      "VF", "VO"
    ]
}'
----

Reponse:

[source,json]
----
{
    "name": "Inception",
    "releaseDate": 2010,
    "rating": 87,
    "languages": [
      "VF", "VO"
    ]
}
----

----
curl -v --location --request PUT '192.168.1.44:8080/api/movies/Inception' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "My Little Pony",
    "releaseDate": 2010,
    "rating": 87,
    "languages": [
      "VF", "VO"
    ]
}'

HTTP/1.1 400
----

----
curl -v --location --request PUT '192.168.1.44:8080/api/movies/Dune' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Dune",
    "releaseDate": 2010,
    "rating": 87,
    "languages": [
      "VF", "VO"
    ]
}'

HTTP/1.1 404
----

== Exp 16: Delete
Ajouter un endpoint DELETE `/api/movies/{name}` qui retourne :

- un status 204 si le film existe et le supprime de la Map,
- un status 400 sinon.

Exemple d'appel:
----
curl -v --location --request DELETE '192.168.1.44:8080/api/movies/Inception'

HTTP/1.1 204
----

----
curl -v --location --request DELETE '192.168.1.44:8080/api/movies/Dune'

HTTP/1.1 404
----

== Exo 17: Liste filtrée

Ajouter sur la liste des films la possibilité de filtrer par note.

Exemple d'appel:
----
curl --location '192.168.1.44:8080/api/movies?rating=99'
----

Reponse:
[source,json]
----
[
  {
    "name": "My Little Pony",
    "releaseDate": 2017,
    "rating": 99,
    "languages": [
      "VO",
      "VFF"
    ]
  }
]
----

== Exo 18: List filtré par header

Sur la liste des films, si le header `Accept-Language` est fourni,
filtrer la liste des résultats

Exemple d'appel:
----
curl --header "Accept-Language: VFF" --location '192.168.1.44:8080/api/movies'
----

Reponse:
[source,json]
----
[
  {
    "name": "My Little Pony",
    "releaseDate": 2017,
    "rating": 99,
    "languages": [
      "VO",
      "VFF"
    ]
  }
]
----

== Exo 19

Spring fourni un framework appelé MockMvc pour faire des requêtes et des assertions lors des tests.

Cette API peut-être injecté en ajoutant `@AutoConfigureMockMvc` à un test.

Un example est fourni dans MovieControllerTest,

La documentation se trouve [ici](https://docs.spring.io/spring-framework/reference/testing/spring-mvc-test-framework.html)

Utiliser ce framework, faire de test de la class MovieController

