spring:
  application:
    name: observability-demo
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  metrics:
    export:
      prometheus:
        enabled: true

---
# Prometheus scrape endpoint will be available at /actuator/prometheus
