openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8099
    description: Generated server url
paths:
  /api/v1/movies/{id}:
    get:
      operationId: findById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionalError'
        '504':
          description: Timeout, must be retry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FunctionalError'
  /api/v1/movies:
    get:
      operationId: findAll
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'

components:
  schemas:
    FunctionalError:
      required:
        - status
        - message
      type: object
      properties:
        status:
          type: string
          example: "404"
        message:
          type: string
          example: "The error message"
    Movie:
      required:
        - id
        - name
        - month
        - year
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 42
        name:
          type: string
          example: "Jurassic Park"
        month:
          type: integer
          example: 5
        year:
          type: integer
          example: 1993
