== Context

Un service de gestion de films est en cours de développement dans une autre équipe.
Pour accéder en lecture, ils ont fournit le contrat link:provided-contract.yaml[provided-contract].

== Projet

Le but de ce projet est de développer une application de gestion d'utilisateur avec leur liste de films favoris.
Les APIs doivent correspondre à ce contrat: link:expected-contract.yaml[expected-contract].

== Contraintes

- découper en 3 couches controlleur / service / repository
- pour appeler le service de gestion de film, il faut utiliser RestTemplate ou le WebClient de Spring
- l'url de base de l'api de film peut changer, elle doit être paramétrable dans les properties
- la base de données doit être une H2
- pour les tests unitaires il faut utiliser:
  - @WebMvcTest pour les controlleurs
  - @DataJpaTest pour les repositories
  - Junit pour pour les services
  - @SpringBootTest pour au moins un test end-to-end (controlleurs -> base h2)
- il faut un log DEBUG à chaque appel reçu par l'application, le profile DEV passe le niveau de log en DEBUG pour les contrôlleurs
- swagger-ui doit être disponible
- il faut exposer métrique `call.movieservice` qui compte le nombres d'appels avec des dimensions sur les codes retours 2xx (200,201...), 4xx et 5xx.

== Rendu

Le code doit être livré dans un dépôt git (gitlab ou github) à la fin du dernier TP.

Un fichier README peut-être rajouté à la racine du projet si besoin (justifier un choix hors des contrats, spécifier un blocage...)
