
spring:
  devtools:
    restart:
      enabled: 'true'
      poll-interval: '2s'
      quiet-period: '1s'
      additional-paths:
      - src/main/kotlin/

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8099