spring:
  application.name: amphi
  datasource:
    url: jdbc:postgresql://localhost:5432/demo-iut
    driverClassName: org.postgresql.Driver
    username: iut
    password: iut
  jpa:
    hibernate.ddl-auto: none
    open-in-view: true
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

app.name: yolo
my:
  enabled: true

