server:
  port: 9999
spring:
  r2dbc:
    url: r2dbc:h2:mem:///test;MODE=PostgreSQL
  flyway:
    enabled: true
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  h2:
    console:
      enabled: true
#logging:
#  level:
#    io.r2dbcV: DEBUG
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metric, shutdown
  server:
    port: 9998