name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install dependencies
        working-directory: ./slides
        run: nci

      - name: Setup playwright
        working-directory: ./slides
        run: pnpm exec playwright install

      - name: Build
        working-directory: ./slides
        run: nr build --base /${{github.event.repository.name}}/
